# Streamlit 전용 Docker Compose 설정

version: '3.8'

services:
  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stt-streamlit-only
    ports:
      - "8501:8501"
    volumes:
      - ./temp:/app/temp
      - ./models:/app/models
      - ./.env:/app/.env:ro  # 읽기 전용으로 환경 파일 마운트
    environment:
      - PYTHONPATH=/app
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_ENABLE_CORS=false
      - STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION=false
      # 한글 지원을 위한 로케일 설정
      - LANG=ko_KR.UTF-8
      - LANGUAGE=ko_KR:ko
      - LC_ALL=ko_KR.UTF-8
      # Python 인코딩 설정
      - PYTHONIOENCODING=utf-8
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s  # ffmpeg 설치 시간을 고려하여 증가
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 1G
          cpus: '0.5'

networks:
  default:
    name: stt-streamlit-network